# ruby to install at `cap deploy:setup` time. If you change this value, you
# need to run `cap ruby:upgrade`. Currently allowed values include: mri,
# src187, ree, ree187
:ruby: ree187

# Name of your application. Should be something with only alphanumerics, hypens
# and underscores.
:application: vote-reports

# Deploy user
:user: deploy

# Timezone to set server's time to. Defaults to UTC
#:time_zone: UTC

# Directory where application is deployed to
:deploy_to: /srv/vote-reports

# Primary domain application will be accessed as 
# :domain: votereports.org

# Domain aliases for applaction. One common use of this is for asset hosts.
:domain_aliases:
  - assets0.votereports.org
  - assets1.votereports.org
  - assets2.votereports.org
  - assets3.votereports.org

# Source control management to use. Defaults to git.
# If you change this value, you will need to run: cap vcs:install
#:scm: git
# Reposistory URI for checking out code at deploy time
:repository: git@github.com:Empact/vote-reports.git

# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
:app_symlinks:
 - system

:root_symlinks:
 - data
 - solr

# Use :shared_config to copy directories straight from your local project
# directory to the server: these are files that you don't have/want in scm.
:local_config:
 - config/database.yml
 - config/secure_variables.rb
 - config/mongo.yml
 - config/facebooker.yml

# The entries in shared_children are created in #{application}/shared
:shared_children:
- log
- pids
- config

# Specify native dependencies of gems. Moonshine comes with some preconfigured
# defaults, but this allows you to add to them. Please file an issue at
# http://github.com/railsmachine/moonshine/issues if there are additional gem
# dependencies moonshine should know about.
:apt_gems:
 :typhoeus:
   - libcurl3
   - libcurl3-dev
 :spatial_adapter:
   - postgresql-8.4-postgis
 :patron:
   - libcurl3
   - libcurl3-dev
 :rsruby:
   - r-base

# Passenger-specific options. Refer to the following templates for details
# about what values are used:
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/passenger.conf.erb 
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/passenger.vhost.erb 
:passenger:
  :max_pool_size: 3

# MySQL-specific options. Refer to the following templates for details about
# what values are used:
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/moonshine.cnf.erb 
:mysql:
  :innodb_buffer_pool_size: 128M

:scout:
  :agent_key: 53a8a406-6297-4ab9-8763-21f8266b9968
